import { Icon } from '@iconify/react';
import { useMemo, useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useDiagramStore } from '@/store/diagramStore';
import { useIacStore } from '@/store/iacStore';
import { ScrollArea } from '@/components/ui/scroll-area';

interface IaCFileBrief {
  id: string;
  name: string;
  type: string;
  content: string;
  size: number;
  status: 'generated' | 'validated' | 'error';
  errors?: string[];
  warnings?: string[];
  autoGenerated?: boolean;
  parameters?: Record<string, unknown>;
}

interface JobsDrawerProps {
  files?: IaCFileBrief[];
  onDownload?: (file: IaCFileBrief) => void;
  onDeploy?: (file: IaCFileBrief) => void;
  height?: number;
}

const JobsDrawer = ({ files = [], onDownload, onDeploy, height = 192 }: JobsDrawerProps) => {
  const [selectedFileId, setSelectedFileId] = useState<string | null>(files.length ? files[0].id : null);
  const nodes = useDiagramStore((state) => state.nodes);
  const edges = useDiagramStore((state) => state.edges);
  const currentBicepTemplate = useIacStore((state) => state.currentBicepTemplate);

  const selectedFile = files.find((f) => f.id === selectedFileId) ?? files[0] ?? null;

  const summary = useMemo(() => {
    const groupNodes = nodes.filter((node) => node.type === 'azure.group');
    const serviceNodes = nodes.length - groupNodes.length;

    const uniqueServices = new Set<string>();
    nodes.forEach((node) => {
      if (node.type === 'azure.group') return;
      const data = (node.data || {}) as Record<string, unknown>;
      const title =
        (typeof data?.service === 'object' && data?.service !== null && (data.service as Record<string, unknown>).title
          ? String((data.service as Record<string, unknown>).title)
          : undefined) ||
        (data?.title ? String(data.title) : undefined);
      if (title) {
        uniqueServices.add(title);
      }
    });

    const warningCount = files.reduce((total, file) => total + (file.warnings?.length ?? 0), 0);
    const errorCount = files.reduce((total, file) => total + (file.errors?.length ?? 0), 0);
    const bicepFiles = files.filter((file) => file.type === 'bicep');
    const terraformFiles = files.filter((file) => file.type === 'terraform');
    const bicepLines = currentBicepTemplate ? currentBicepTemplate.split(/\r?\n/).length : 0;

    return {
      nodeCount: nodes.length,
      groupCount: groupNodes.length,
      serviceNodeCount: Math.max(serviceNodes, 0),
      edgeCount: edges.length,
      uniqueServices: uniqueServices.size,
      fileCount: files.length,
      bicepFileCount: bicepFiles.length,
      terraformFileCount: terraformFiles.length,
      warningCount,
      errorCount,
      bicepLines,
      hasBicepTemplate: !!currentBicepTemplate,
    };
  }, [currentBicepTemplate, edges.length, files, nodes]);

  const SummaryCard = ({
    icon,
    label,
    value,
    helper,
  }: {
    icon: string;
    label: string;
    value: string | number;
    helper?: string;
  }) => (
    <div className="rounded-lg border border-border/30 bg-muted/10 px-4 py-3 shadow-sm shadow-black/5">
      <div className="flex items-center gap-3">
        <div className="rounded-md bg-primary/10 p-2 text-primary">
          <Icon icon={icon} className="text-lg" />
        </div>
        <div>
          <div className="text-xs uppercase tracking-wide text-muted-foreground">{label}</div>
          <div className="text-lg font-semibold text-foreground">{value}</div>
          {helper && <div className="text-[11px] text-muted-foreground/80">{helper}</div>}
        </div>
      </div>
    </div>
  );

  return (
    <div 
      className="glass-panel border-t border-border/50" 
      style={{ height: `${height}px` }}
      data-resizable-footer
    >
      <Tabs defaultValue="summary" className="h-full flex flex-col">
        <TabsList className="mx-4 mt-3 grid w-auto grid-cols-4">
          <TabsTrigger value="summary" className="gap-2">
            <Icon icon="mdi:chart-box" />
            Summary
          </TabsTrigger>
          <TabsTrigger value="iac" className="gap-2">
            <Icon icon="mdi:code-json" />
            IaC
          </TabsTrigger>
          <TabsTrigger value="validation" className="gap-2">
            <Icon icon="mdi:check-circle" />
            Validation
          </TabsTrigger>
          <TabsTrigger value="logs" className="gap-2">
            <Icon icon="mdi:text-box" />
            Deploy Logs
          </TabsTrigger>
        </TabsList>
        <ScrollArea className="flex-1 p-2 space-y-2 min-h-0">
          <TabsContent value="summary" className="flex-1 overflow-y-auto px-4 pb-4">
            {summary.nodeCount === 0 && summary.fileCount === 0 ? (
              <div className="text-center py-6">
                <Icon icon="mdi:information" className="text-3xl text-muted-foreground mx-auto mb-2" />
                <p className="text-sm text-muted-foreground">
                  Start by adding services or generating IaC to see project insights.
                </p>
              </div>
            ) : (
              <div className="py-4 space-y-4">
                <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                  <SummaryCard
                    icon="mdi:graph-outline"
                    label="Nodes"
                    value={summary.nodeCount}
                    helper={`${summary.serviceNodeCount} services / ${summary.groupCount} groups`}
                  />
                  <SummaryCard icon="mdi:vector-line" label="Connections" value={summary.edgeCount} />
                  <SummaryCard
                    icon="mdi:view-dashboard"
                    label="Unique Services"
                    value={summary.uniqueServices}
                    helper="Distinct service titles in the canvas"
                  />
                  <SummaryCard
                    icon="mdi:file-cog"
                    label="IaC Files"
                    value={summary.fileCount}
                    helper={`${summary.bicepFileCount} bicep • ${summary.terraformFileCount} terraform`}
                  />
                  <SummaryCard
                    icon="mdi:code-braces"
                    label="Bicep Lines"
                    value={summary.bicepLines}
                    helper={summary.hasBicepTemplate ? 'Auto-generated template ready' : 'Generate to populate'}
                  />
                  <SummaryCard
                    icon="mdi:shield-alert"
                    label="Validation Issues"
                    value={summary.warningCount + summary.errorCount}
                    helper={`${summary.warningCount} warnings • ${summary.errorCount} errors`}
                  />
                </div>

                {summary.hasBicepTemplate ? (
                  <div className="rounded-lg border border-border/40 bg-muted/5 px-4 py-3">
                    <div className="flex items-center justify-between text-xs uppercase text-muted-foreground">
                      <span>Latest Bicep template</span>
                      <span className="text-[10px] text-muted-foreground/70">Editable in inspector</span>
                    </div>
                    <div className="mt-2 text-sm text-muted-foreground">
                      Track changes directly in the inspector for a detailed, resource-level edit experience.
                    </div>
                  </div>
                ) : (
                  <div className="rounded-lg border border-dashed border-border/40 bg-muted/5 px-4 py-3 text-xs text-muted-foreground">
                    No Bicep template yet — trigger generation from the chat or IaC panel to bootstrap deployment assets.
                  </div>
                )}
              </div>
            )}
          </TabsContent>

          <TabsContent value="iac" className="flex-1 overflow-y-auto px-4 pb-4">
            {files.length === 0 ? (
              <div className="text-center py-6">
                <Icon icon="mdi:code-json" className="text-3xl text-muted-foreground mx-auto mb-2" />
                <p className="text-sm text-muted-foreground">No generated IaC files yet</p>
              </div>
            ) : (
              <div className="space-y-3">
                {files.map((file) => (
                  <div key={file.id} className="flex items-center justify-between p-2 rounded border border-border/30">
                    <div className="flex items-center gap-3">
                      <div className="w-8 text-center text-muted-foreground">
                        <Icon icon={file.type === 'bicep' ? 'mdi:file-binary' : 'mdi:file-code'} />
                      </div>
                      <div>
                        <div className="font-medium">{file.name}</div>
                        <div className="text-xs text-muted-foreground">{Math.round(file.size)} bytes • {file.status}</div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <button
                        className="btn btn-ghost btn-sm"
                        onClick={() => {
                          setSelectedFileId(file.id);
                        }}
                      >
                        View
                      </button>
                      <button
                        className="btn btn-outline btn-sm"
                        onClick={() => (onDownload ? onDownload(file) : (() => {
                          const blob = new Blob([file.content], { type: 'text/plain' });
                          const url = URL.createObjectURL(blob);
                          const a = document.createElement('a');
                          a.href = url;
                          a.download = file.name;
                          document.body.appendChild(a);
                          a.click();
                          a.remove();
                          URL.revokeObjectURL(url);
                        })())}
                      >
                        Download
                      </button>
                      <button
                        className="btn btn-primary btn-sm"
                        onClick={() => (onDeploy ? onDeploy(file) : console.log('Deploy', file))}
                      >
                        Deploy
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </TabsContent>

          <TabsContent value="validation" className="flex-1 overflow-y-auto px-4 pb-4">
            {selectedFile ? (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Validation for {selectedFile.name}</div>
                    <div className="text-xs text-muted-foreground">Status: {selectedFile.status}</div>
                  </div>
                </div>

                <div>
                  <div className="font-semibold">Warnings</div>
                  {selectedFile.warnings && selectedFile.warnings.length ? (
                    <ul className="list-disc pl-6 text-sm">
                      {selectedFile.warnings.map((w, i) => (
                        <li key={i}>{w}</li>
                      ))}
                    </ul>
                  ) : (
                    <div className="text-sm text-muted-foreground">No warnings</div>
                  )}
                </div>

                <div>
                  <div className="font-semibold">Errors</div>
                  {selectedFile.errors && selectedFile.errors.length ? (
                    <ul className="list-disc pl-6 text-sm text-destructive">
                      {selectedFile.errors.map((e, i) => (
                        <li key={i}>{e}</li>
                      ))}
                    </ul>
                  ) : (
                    <div className="text-sm text-muted-foreground">No errors</div>
                  )}
                </div>
              </div>
            ) : (
              <div className="text-center py-6">
                <Icon icon="mdi:check-circle" className="text-3xl text-muted-foreground mx-auto mb-2" />
                <p className="text-sm text-muted-foreground">Select a file in the IaC tab to see validation</p>
              </div>
            )}
          </TabsContent>

          <TabsContent value="logs" className="flex-1 overflow-y-auto px-4 pb-4">
            <div className="text-center py-6">
              <Icon icon="mdi:text-box" className="text-3xl text-muted-foreground mx-auto mb-2" />
              <p className="text-sm text-muted-foreground">Live deployment logs will stream here</p>
            </div>
          </TabsContent>
        </ScrollArea>
      </Tabs>
    </div>
  );
};

export default JobsDrawer;
