// Prefer using the prebuilt JSON generated by scripts/buildGcpServices.js
import gcpServicesJson from './gcpServices.json';

export type GcpService = {
  id: string;
  title: string;
  description: string;
  iconPath: string;
  category: string;
};

export const gcpServices: GcpService[] = (gcpServicesJson as GcpService[]) || [];
// If the build script couldn't derive categories (many icons live at the
// top-level), infer a category from the title using simple keyword rules so
// the palette can present useful groups.
function inferCategoryFromTitle(title: string): string {
  const t = title.toLowerCase();
  if (/compute|engine|gke|vm|instance|bare-metal/.test(t)) return 'Compute';
  if (/storage|bucket|disk|filestore|persistent|cloud-storage|gcs/.test(t)) return 'Storage';
  if (/network|vpc|vpn|load|router|routes|nat|cdn|interconnect|peering/.test(t)) return 'Networking';
  if (/sql|spanner|bigquery|bigtable|datastore|firestore|database|dataproc|dataplex/.test(t)) return 'Databases';
  if (/pubsub|stream|dataflow|datastream|eventarc|kafka|messag/.test(t)) return 'Messaging';
  if (/container|kubernetes|gke|anthos|container-registry|cloud run|cloud-run/.test(t)) return 'Containers';
  if (/function|cloud functions|lambda|run/.test(t)) return 'Serverless';
  if (/ml|ai|vertex|automl|tensorflow|vision|nlp|recommend|ai-platform|vertex-ai/.test(t)) return 'AI / ML';
  if (/security|iam|identity|certificate|armor|security-command|phishing/.test(t)) return 'Security';
  if (/monitor|logging|trace|stackdriver|ops|health|error|profiler/.test(t)) return 'Observability';
  if (/devops|build|deploy|artifact|cloud-build|cloud-deploy|ci|cd/.test(t)) return 'DevOps';
  if (/api|apigee|endpoints|gateway/.test(t)) return 'APIs';
  if (/iot|iot-core|iot-edge|fleet|edge/.test(t)) return 'IoT & Edge';
  return 'Other';
}

export const gcpServiceCategories: string[] = Array.from(
  new Set(
    gcpServices.map((s) => (s.category && s.category !== 'Other' ? s.category : inferCategoryFromTitle(s.title)))
  )
).sort();

// Normalize services so each has a reasonable category
export const normalizedGcpServices: GcpService[] = gcpServices.map((s) => ({
  ...s,
  category: s.category && s.category !== 'Other' ? s.category : inferCategoryFromTitle(s.title),
}));

export default normalizedGcpServices;
